// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/services/dynamodb.proto

package dynamodb // import "github.com/mattrayner/monzo-roundup/types/services/dynamodb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserInput struct {
	AccountID            string   `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInput) Reset()         { *m = GetUserInput{} }
func (m *GetUserInput) String() string { return proto.CompactTextString(m) }
func (*GetUserInput) ProtoMessage()    {}
func (*GetUserInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_dynamodb_98745f1fdc502f92, []int{0}
}
func (m *GetUserInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInput.Unmarshal(m, b)
}
func (m *GetUserInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInput.Marshal(b, m, deterministic)
}
func (dst *GetUserInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInput.Merge(dst, src)
}
func (m *GetUserInput) XXX_Size() int {
	return xxx_messageInfo_GetUserInput.Size(m)
}
func (m *GetUserInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInput proto.InternalMessageInfo

func (m *GetUserInput) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

type GetUserOutput struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserOutput) Reset()         { *m = GetUserOutput{} }
func (m *GetUserOutput) String() string { return proto.CompactTextString(m) }
func (*GetUserOutput) ProtoMessage()    {}
func (*GetUserOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_dynamodb_98745f1fdc502f92, []int{1}
}
func (m *GetUserOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserOutput.Unmarshal(m, b)
}
func (m *GetUserOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserOutput.Marshal(b, m, deterministic)
}
func (dst *GetUserOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserOutput.Merge(dst, src)
}
func (m *GetUserOutput) XXX_Size() int {
	return xxx_messageInfo_GetUserOutput.Size(m)
}
func (m *GetUserOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserOutput proto.InternalMessageInfo

func (m *GetUserOutput) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserInput struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserInput) Reset()         { *m = UpdateUserInput{} }
func (m *UpdateUserInput) String() string { return proto.CompactTextString(m) }
func (*UpdateUserInput) ProtoMessage()    {}
func (*UpdateUserInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_dynamodb_98745f1fdc502f92, []int{2}
}
func (m *UpdateUserInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserInput.Unmarshal(m, b)
}
func (m *UpdateUserInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserInput.Marshal(b, m, deterministic)
}
func (dst *UpdateUserInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserInput.Merge(dst, src)
}
func (m *UpdateUserInput) XXX_Size() int {
	return xxx_messageInfo_UpdateUserInput.Size(m)
}
func (m *UpdateUserInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserInput.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserInput proto.InternalMessageInfo

func (m *UpdateUserInput) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserOutput struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserOutput) Reset()         { *m = UpdateUserOutput{} }
func (m *UpdateUserOutput) String() string { return proto.CompactTextString(m) }
func (*UpdateUserOutput) ProtoMessage()    {}
func (*UpdateUserOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_dynamodb_98745f1fdc502f92, []int{3}
}
func (m *UpdateUserOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserOutput.Unmarshal(m, b)
}
func (m *UpdateUserOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserOutput.Marshal(b, m, deterministic)
}
func (dst *UpdateUserOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserOutput.Merge(dst, src)
}
func (m *UpdateUserOutput) XXX_Size() int {
	return xxx_messageInfo_UpdateUserOutput.Size(m)
}
func (m *UpdateUserOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserOutput.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserOutput proto.InternalMessageInfo

func (m *UpdateUserOutput) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	AccountID            string   `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	AuthToken            string   `protobuf:"bytes,2,opt,name=authToken,proto3" json:"authToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_dynamodb_98745f1fdc502f92, []int{4}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *User) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *User) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserInput)(nil), "dynamodb.GetUserInput")
	proto.RegisterType((*GetUserOutput)(nil), "dynamodb.GetUserOutput")
	proto.RegisterType((*UpdateUserInput)(nil), "dynamodb.UpdateUserInput")
	proto.RegisterType((*UpdateUserOutput)(nil), "dynamodb.UpdateUserOutput")
	proto.RegisterType((*User)(nil), "dynamodb.User")
}

func init() {
	proto.RegisterFile("types/services/dynamodb.proto", fileDescriptor_dynamodb_98745f1fdc502f92)
}

var fileDescriptor_dynamodb_98745f1fdc502f92 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x65, 0xb5, 0x68, 0x3b, 0xd6, 0x0f, 0x72, 0xd0, 0xba, 0x28, 0xc8, 0x9e, 0x3c, 0xe8, 0x2e,
	0xb4, 0xe8, 0x41, 0xf1, 0x52, 0x17, 0xa4, 0x27, 0xa1, 0xd8, 0x8b, 0xb7, 0xfd, 0x98, 0xda, 0x22,
	0x9b, 0x84, 0x64, 0x22, 0xac, 0x7f, 0xc1, 0x3f, 0x2d, 0x1b, 0x53, 0xd3, 0xe2, 0x07, 0x7a, 0x9c,
	0xf7, 0xde, 0xe4, 0xe5, 0x3d, 0x06, 0x8e, 0xa9, 0x96, 0xa8, 0x13, 0x8d, 0xea, 0x65, 0x5e, 0xa0,
	0x4e, 0xca, 0x9a, 0x67, 0x95, 0x28, 0xf3, 0x58, 0x2a, 0x41, 0x82, 0xb5, 0x17, 0x73, 0x74, 0x06,
	0xdd, 0x3b, 0xa4, 0x89, 0x46, 0x35, 0xe2, 0xd2, 0x10, 0x3b, 0x82, 0x4e, 0x56, 0x14, 0xc2, 0x70,
	0x1a, 0xa5, 0xbd, 0xe0, 0x24, 0x38, 0xed, 0x8c, 0x3d, 0x10, 0x0d, 0x60, 0xdb, 0xa9, 0xef, 0x0d,
	0x35, 0xf2, 0x08, 0x5a, 0x46, 0xa3, 0xb2, 0xca, 0xad, 0xfe, 0x4e, 0xfc, 0xe9, 0xd3, 0x68, 0xc6,
	0x96, 0x8b, 0x2e, 0x60, 0x77, 0x22, 0xcb, 0x8c, 0xd0, 0xbb, 0xfc, 0x65, 0xed, 0x12, 0xf6, 0xfc,
	0xda, 0x3f, 0xec, 0xa6, 0xd0, 0x6a, 0xa6, 0xdf, 0x93, 0x58, 0xd6, 0xd0, 0xec, 0x41, 0x3c, 0x23,
	0xef, 0xad, 0x39, 0x76, 0x01, 0xb0, 0x08, 0xba, 0x0a, 0xa7, 0x0a, 0xb5, 0x13, 0xac, 0x5b, 0xc1,
	0x0a, 0xd6, 0x7f, 0x0b, 0xa0, 0x9d, 0x5a, 0xff, 0x74, 0xc8, 0xae, 0x60, 0xd3, 0x15, 0xc3, 0xf6,
	0xfd, 0xaf, 0x96, 0x9b, 0x0d, 0x0f, 0xbe, 0xe0, 0x2e, 0xd4, 0x2d, 0x80, 0x0f, 0xca, 0x0e, 0x97,
	0x42, 0xad, 0xb6, 0x16, 0x86, 0xdf, 0x51, 0x1f, 0x8f, 0x0c, 0x6f, 0x1e, 0xaf, 0x9f, 0xe6, 0x34,
	0x33, 0x79, 0x5c, 0x88, 0x2a, 0xa9, 0x32, 0x22, 0x95, 0xd5, 0x1c, 0x55, 0x52, 0x09, 0xfe, 0x2a,
	0xce, 0x95, 0x30, 0xbc, 0x34, 0x32, 0xf9, 0xe1, 0x2c, 0xf2, 0x0d, 0x7b, 0x17, 0x83, 0xf7, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x67, 0x05, 0xfb, 0x53, 0x38, 0x02, 0x00, 0x00,
}
